### PR TITLE
Use asgiref when available instead of thread locals (#176)

### PR DESCRIPTION
**Pull request by gurkanindibay**

### CODE REVIEW

**Comment by gurkanindibay** [comment]
@darwing1210 Could you check this PR which fixes merge conflicts with the new changes

**Comment by paddyobrien** [comment]
@gurkanindibay any chance you could cut a new release with this in it? Trying to use this project in ASGI and running into issues that I think this change will fix

**Comment by gurkanindibay** [comment]
@paddyobrien Thanks for your interest in the project. We released 4.1.0 version. 
Thanks

**Comment by paddyobrien** [comment]
@gurkanindibay Thank you so much! ❤️

**Pull request merged**
