### PR TITLE
Add failing test case for #54

### PR DESCRIPTION
**Pull request by ledburyb**

### CODE REVIEW

**Comment by louiseGrandjonc** [comment]
Thank you @ledburyb, I'm going to look into fixing this. If you can sign the contribution license agreement in the same time, that would be great :)

**Comment by ledburyb** [comment]
@louiseGrandjonc - I'm not sure the license agreement thing is working. I'm not getting an email.

**Comment by louiseGrandjonc** [comment]
It's supposed to take 24h apparently. If it doesn't arrive today I will ask people in my team

**Comment by louiseGrandjonc** [comment]
If you can test this branch, I put a fix: https://github.com/citusdata/django-multitenant/pull/65 

It makes the query pass, and if the query generated was bad because lacking he condition, it would fail with a proper message on the query.

**Comment by ledburyb** [comment]
👍 Seems to work perfectly in all our test cases.

**Comment by louiseGrandjonc** [comment]
#65 was merged into master, I will release a new version this week after reviewing other PRs

**Pull request closed without merging**
