### PR TITLE
Added backend for PostGIS

### PR DESCRIPTION
**Pull request by OmenApps**
Minor changes to allow use of PostGIS rather than vanilla Postgres

### CODE REVIEW

**Comment by OmenApps** [comment]
Any comments?

**Comment by louiseGrandjonc** [comment]
Hi @OmenApps,

Could you add unit tests to illustrate the use case?

**Comment by finch-wren** [comment]
Can we expect this to ber merged anytime soon?

**Comment by JelteF** [comment]
@finch-wren if you could contribute some tests that show the usage of it, I'd be happy to get this merged. Without tests it's hard for me to understand what this is doing though, since I have very little experience with PostGIS.

**Comment by serprex** [comment]
Related #110

**Comment by jonels-msft** [comment]
@OmenApps thanks for the contribution. As it's been open for several years, I'm going to close this PR.

Feel free to re-open if you want to include tests.

**Pull request closed without merging**
