### PR TITLE
With TENANT_STRICT_MODE set you cannot query or bulk create

### PR DESCRIPTION
**Pull request by nickittynack**
Hello, this change would cause the library to throw exceptions if `TENANT_STRICT_MODE` is set to True. Rationale being if there is no tenant you should not be able to query all rows.

Apologies if this is not the intent of `TENANT_STRICT_MODE`. I can add/fix up appropriate tests, wanted to check if this sort of change would be alright.

### CODE REVIEW

**Comment by nickittynack** [comment]
@microsoft-github-policy-service agree company="GenesisCare"

**Comment by gurkanindibay** [comment]
@nickittynack Thanks for your contribution ❤️. Could you add test cases to test these code blocks

**Review by gurkanindibay — CHANGES_REQUESTED** [review]
Thanks

**Comment by nickittynack** [comment]
Apologies the project driving the need for this library has headed in a different direction for tenancy, so I will close this for now. Thank you for your time

**Pull request closed without merging**
